### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mrelliot69** [bennothommo/packager#3]
Where ican find the docs on how to use the library?
Not sure how i can define a directory where i want the packages to be installed insted of vendor dir

**Comment by bennothommo** [comment]
We haven't really documented this library yet because it's still in active development. However, I would imagine you can change the `vendor` directory to something else by adding the following to your `composer.json` file:

```json
"config": {
    "vendor-dir": "<custom-vendor-path>"
}
```

https://getcomposer.org/doc/06-config.md#vendor-dir
